data = [


["Alzheimer", "Difficulte a s'endormir" ,1]      ,  
["Alzheimer", "Essoufflement" ,1] ,
["Alzheimer", "Fatigue",2]      ,
["Alzheimer", "Gonflement des jambes et des chevilles",1] ,
["Alzheimer", "Naus?es",1],
["Alzheimer", "Perte m?moire",5],
["Alzheimer", "Soif excessive",1] ,
["Alzheimer", "Tristesse",1]      ,
["Anemia", "Difficult? ? s'endormir",3]   ,
["Anemia", "Douleur",1]   ,
["Anemia", "Essoufflement",3]     ,
["Anemia", "Fatigue",18]   ,
["Anemia", "Gain ou perte de poids inexpliqu?e",2]   ,
["Anemia", "Gonflement des jambes et des chevilles",2] ,   
["Anemia", "Jauneur de la peau",1]        ,
["Anemia", "Nervosit?",5] ,
["Anemia", "Perte m?moire",1]     ,
["Anemia", "Soif excessive",1]    ,
["Anemia", "Tristesse",10] ,
["Anemia", "Vision floue",1]      ,
["Anxiety", "Difficult? ? s'endormir",5]  ,
["Anxiety", "Douleur",1]  ,
["Anxiety", "Essoufflement",2]    ,
["Anxiety", "Fatigue",7]  ,
["Anxiety", "Gain ou perte de poids inexpliqu?e" ,2],       
["Anxiety", "Jauneur de la peau",1]       ,
["Anxiety", "Naus?es",1]  ,
["Anxiety", "Nervosit?",17]        ,
["Anxiety", "Tristesse",10]        ,
["Anxiety", "Vision floue" ,2]     ,
["Asthma", "Difficult? ? s'endormir",1]   ,
["Asthma", "Douleur",1]   ,
["Asthma", "Essoufflement",16]     ,
["Asthma", "Fatigue",7]   ,
["Asthma", "Gonflement des jambes et des chevilles",3]    ,
["Asthma", "Nervosit?",2] ,
["Asthma", "Perte m?moire",1]     ,
["Asthma", "Soif excessive",7]    ,
["Asthma", "Tristesse",2] ,
["Asthma", "Vision floue",1]      ,
["Cancer", "Difficult? ? s'endormir",1]  , 
["Cancer", "Douleur",22]  ,
["Cancer", "Essoufflement",1]     ,
["Cancer", "Fatigue",6]   ,
["Cancer", "Gain ou perte de poids inexpliqu?e",1] ,       
["Cancer", "Gonflement des jambes et des chevilles",10]  ,  
["Cancer", "Jauneur de la peau",6]        ,
["Cancer", "Nervosit?",1] ,
["Cancer", "Soif excessive",6]    ,
["Cancer", "Tristesse",3] ,
["Cancer", "Vision floue",5] ,
["Depression", "Difficult? ? s'endormir",15]       ,
["Depression", "Douleur",3]       ,
["Depression", "Essoufflement",2] ,
["Depression", "Fatigue",13]       ,
["Depression", "Gain ou perte de poids inexpliqu?e",3] ,   
["Depression", "Gonflement des jambes et des chevilles",1] ,       
["Depression", "Naus?es",1]       ,
["Depression", "Nervosit?",10]     ,
["Depression", "Perte m?moire",1] ,
["Depression", "Soif excessive",3]        ,
["Depression", "Tristesse",33]     ,
["Depression", "Vision floue",8]        ,
["Diabetes", "Douleur",6] ,
["Diabetes", "Essoufflement",7]   ,
["Diabetes", "Fatigue",6] ,
["Diabetes", "Gain ou perte de poids inexpliqu?e",4]   ,  
["Diabetes", "Gonflement des jambes et des chevilles",3]  ,
["Diabetes", "Jauneur de la peau",3]      ,
["Diabetes", "Perte m?moire",1]   ,
["Diabetes", "Soif excessive",33]  ,
["Diabetes", "Tristesse",3]       ,
["Diabetes", "Vision floue",18]    ,
["HeartDisease", "Douleur",2]     ,
["HeartDisease", "Essoufflement",1]       ,
["HeartDisease", "Fatigue",5]     ,
["HeartDisease", "Gain ou perte de poids inexpliqu?e",1]  ,
["HeartDisease", "Gonflement des jambes et des chevilles",1] ,     
["HeartDisease", "Soif excessive",1]      ,
["HeartDisease", "Vision floue",2]        ,
["Hypertension", "Difficult? ? s'endormir",3]     ,
["Hypertension", "Douleur",5]     ,
["Hypertension", "Essoufflement",1]       ,
["Hypertension", "Fatigue",5]     ,
["Hypertension", "Gain ou perte de poids inexpliqu?e",9]  ,
["Hypertension", "Gonflement des jambes et des chevilles",2]  ,    
["Hypertension", "Nervosit?",2]   ,
["Hypertension", "Soif excessive",18]      ,
["Hypertension", "Tristesse",8]   ,
["Hypertension", "Vision floue",36]        ,
["Insomnia", "Difficult? ? s'endormir",20] ,
["Insomnia", "Douleur",1] ,
["Insomnia", "Essoufflement",1]   ,
["Insomnia", "Fatigue",4]  ,
["Insomnia", "Gain ou perte de poids inexpliqu?e",1]   ,   
["Insomnia", "Naus?es",3] ,
["Insomnia", "Nervosit?",5]       ,
["Insomnia", "Perte m?moire",1]   ,
["Insomnia", "Tristesse",15]       ,
["Insomnia", "Vision floue",3]    ,
["KidneyDisease", "Douleur",10]    ,
["KidneyDisease", "Essoufflement",3]   ,   
["KidneyDisease", "Fatigue",4]    ,
["KidneyDisease", "Gain ou perte de poids inexpliqu?e",1] ,
["KidneyDisease", "Gonflement des jambes et des chevilles",16]   ,  
["KidneyDisease", "Jauneur de la peau",3] ,
["KidneyDisease", "Perte m?moire",1]      ,
["KidneyDisease", "Soif excessive",3]     ,
["KidneyDisease", "Tristesse",1]  ,
["KidneyDisease", "Vision floue",2]       ,
["LiverDisease", "Douleur",5]     ,
["LiverDisease", "Fatigue",1]     ,
["LiverDisease", "Gonflement des jambes et des chevilles",3] ,     
["LiverDisease", "Jauneur de la peau",6]  ,
["LiverDisease", "Nervosit?",1]   ,
["LiverDisease", "Soif excessive",1]     ,
["Migraine", "Difficult? ? s'endormir",3] ,
["Migraine", "Naus?es",4] ,
["Migraine", "Nervosit?",1]       ,
["Migraine", "Perte m?moire",1]   ,
["Migraine", "Tristesse",1]       ,
["Obesity", "Difficult? ? s'endormir",1]  ,
["Obesity", "Douleur",3]  ,
["Obesity", "Essoufflement",3]    ,
["Obesity", "Fatigue", 12],
["Obesity", "Gain ou perte de poids inexpliqu?e",2]   ,    
["Obesity", "Gonflement des jambes et des chevilles",1]  , 
["Obesity", "Nervosit?",2]        ,
["Obesity", "Perte m?moire",1]    ,
["Obesity", "Soif excessive",4]   ,
["Obesity", "Tristesse",3]        ,
["Obesity", "Vision floue",2]     ,
["Thyroid", "Difficult? ? s'endormir",1]  ,
["Thyroid", "Douleur",1]  ,
["Thyroid", "Fatigue",4]  ,
["Thyroid", "Gain ou perte de poids inexpliqu?e",15]    ,   
["Thyroid", "Gonflement des jambes et des chevilles",1]  , 
["Thyroid", "Nervosit?",2]        ,
["Thyroid", "Soif excessive",4]   ,
["Thyroid", "Tristesse",3]        ,
["Thyroid", "Vision floue",9]     ,
]

# Initialiser un dictionnaire pour stocker les symptômes les plus fréquents par maladie
max_freq_symptoms = {}

# Parcourir les entrées de données
for entry in data:
    # Extraire la maladie, le symptôme et la fréquence
    disease, symptom, frequency = entry
    
    # Convertir la fréquence en entier
    frequency = int(frequency)
    
    # Vérifier si la maladie est déjà dans le dictionnaire
    if disease not in max_freq_symptoms:
        # Si non, ajouter la maladie avec le symptôme et la fréquence actuels
        max_freq_symptoms[disease] = (symptom, frequency)
    else:
        # Si oui, mettre à jour le symptôme si la fréquence est plus élevée
        current_frequency = max_freq_symptoms[disease][1]
        if frequency > current_frequency:
            max_freq_symptoms[disease] = (symptom, frequency)

# Afficher les résultats
for disease, (symptom, frequency) in max_freq_symptoms.items():
    print(f"{disease}: {symptom} avec une fréquence de {frequency}")
